### ISSUE TITLE
Save configuration atomically

### ISSUE THREAD

**Issue by earlchew** [fanciulli/v-conf#3]
As a user, I want the configuration to be saved atomically, so that I can be certain that I will always be able to read a valid configuration.

My reading of the implementation suggests that `writeJsonSync()` is not atomic, meaning that it is possible that on program or computer failure only a fragment of the previously complete configuration remains.

```javascript
Config.prototype.save=function()
{
    var self=this;

    if(self.saved===false)
    {
        self.saved=true;

        if(self.syncSave)
            fs.writeJsonSync(self.filePath,self.data);
        else fs.writeJson(self.filePath,self.data);
    }
```

See https://www.npmjs.com/package/write-file-atomic for ideas.

**Comment by fanciulli** [comment]
hello @earlchew ,

the use of writeJson and writeJsonSync reflect the need to synchronize the code with the data write on disk without always recurring to callbacks. I see the need of having atomic write on disk. I'll udpate the method to also support atomic writes.
Thank for your suggestion!

**Comment by fanciulli** [comment]
Hello @earlchew ,
i just committed the update.
